# ========================================
# API Gateway - Application Configuration
# ========================================
# This file connects to Config Server
# All actual configs are managed centrally in Config Server
# ========================================

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: false
